### ISSUE TITLE
게시판 api 만들기

### ISSUE THREAD

**Issue by IronKim** [IronKim/fs-project-board#1]

**Comment by IronKim** [comment]
api를 만든다.

- [x] API 설계
- [x] API 테스트 정의
- [x] API 구현
  - [x] 게시글 api
  - [x] 댓글 api

**Comment by dbwpghks56** [comment]
빨리 만들어주세요~

**Comment by IronKim** [comment]
api 설계 완료
- (링크 붙일 예정)
